org: hanselmrojas
app: pirpos-img
service: pirpos-img

frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  environment:
    AWS_KEY: ${param:AWS_KEY}
    AWS_SECRET: ${param:AWS_SECRET}
    AWS_S3_BUCKET_NAME: ${param:AWS_S3_BUCKET_NAME}
    MONGO_HOST: ${param:MONGO_HOST}
    MONGO_USER: ${param:MONGO_USER}
    MONGO_PASS: ${param:MONGO_PASS}
    MONGO_DB: ${param:MONGO_DB}

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

